import { PatientMaster } from "../app/modules/Clinical Module/patient-list/patient-list.component";

export let l_patient_master_list = [
   {
      "patientId": "06a01eef-406e-4dba-b378-f91e29aae40d",
      "mrn_no": "MRN001",
      "first_name": "Arjun",
      "middle_name": "Kumar",
      "last_name": "Sharma",
      "date_of_birth": "1990-02-10",
      "age_in_years": 35,
      "age_in_months": 420,
      "age_in_days": 12775,
      "gender": 1,
      "marital_status": "Single",
      "blood_group": "B+",
      "nationality": "Indian",
      "address": "12, Gali No. 5, New Delhi",
      "mobile_no": "+91-9876543210",
      "email_id": "arjun.sharma@example.com",
      "patient_status": "Active",
      "patient_login": "arjun_sharma",
      "patient_password": "password123",
      "country": "India",
      "city": "New Delhi",
      "district": "Central Delhi",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "a74f870f-915c-46e4-83c3-ba44b7f4fb0b",
      "mrn_no": "MRN002",
      "first_name": "Priya",
      "middle_name": "Singh",
      "last_name": "Verma",
      "date_of_birth": "1985-11-22",
      "age_in_years": 39,
      "age_in_months": 468,
      "age_in_days": 14175,
      "gender": 2,
      "marital_status": "Married",
      "blood_group": "A+",
      "nationality": "Indian",
      "address": "45, Sector 22, Gurgaon, Haryana",
      "mobile_no": "+91-9123456789",
      "email_id": "priya.verma@example.com",
      "patient_status": "Active",
      "patient_login": "priya_verma",
      "patient_password": "password456",
      "country": "India",
      "city": "Gurgaon",
      "district": "Gurgaon",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "b3efcf38-2f77-4a18-8cd4-16cb47b134bc",
      "mrn_no": "MRN003",
      "first_name": "Ravi",
      "middle_name": "Chand",
      "last_name": "Joshi",
      "date_of_birth": "1992-06-13",
      "age_in_years": 32,
      "age_in_months": 384,
      "age_in_days": 11520,
      "gender": 1,
      "marital_status": "Single",
      "blood_group": "O-",
      "nationality": "Indian",
      "address": "123, Park Road, Pune, Maharashtra",
      "mobile_no": "+91-9812345678",
      "email_id": "ravi.joshi@example.com",
      "patient_status": "Active",
      "patient_login": "ravi_joshi",
      "patient_password": "password789",
      "country": "India",
      "city": "Pune",
      "district": "Pune",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "bc40de9d-4984-4a32-9916-ad1dd084fd22",
      "mrn_no": "MRN004",
      "first_name": "Ananya",
      "middle_name": "Sharma",
      "last_name": "Iyer",
      "date_of_birth": "1995-08-15",
      "age_in_years": 29,
      "age_in_months": 348,
      "age_in_days": 10440,
      "gender": 2,
      "marital_status": "Married",
      "blood_group": "AB+",
      "nationality": "Indian",
      "address": "200, MG Road, Bangalore, Karnataka",
      "mobile_no": "+91-9908765432",
      "email_id": "ananya.iyer@example.com",
      "patient_status": "Active",
      "patient_login": "ananya_iyer",
      "patient_password": "password101",
      "country": "India",
      "city": "Bangalore",
      "district": "Bangalore",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "f5049050-80ce-41e0-a767-c13492f0a353",
      "mrn_no": "MRN005",
      "first_name": "Suresh",
      "middle_name": "Ram",
      "last_name": "Patel",
      "date_of_birth": "1988-03-04",
      "age_in_years": 37,
      "age_in_months": 444,
      "age_in_days": 13320,
      "gender": 1,
      "marital_status": "Single",
      "blood_group": "O+",
      "nationality": "Indian",
      "address": "22, Sardar Patel Nagar, Ahmedabad, Gujarat",
      "mobile_no": "+91-9001234567",
      "email_id": "suresh.patel@example.com",
      "patient_status": "Active",
      "patient_login": "suresh_patel",
      "patient_password": "password202",
      "country": "India",
      "city": "Ahmedabad",
      "district": "Ahmedabad",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "f1b0c742-2838-4245-b384-95a75efcae35",
      "mrn_no": "MRN006",
      "first_name": "Neha",
      "middle_name": "Kumari",
      "last_name": "Yadav",
      "date_of_birth": "1997-01-29",
      "age_in_years": 28,
      "age_in_months": 336,
      "age_in_days": 10080,
      "gender": 2,
      "marital_status": "Married",
      "blood_group": "B+",
      "nationality": "Indian",
      "address": "58, Kavi Nagar, Ghaziabad, Uttar Pradesh",
      "mobile_no": "+91-9956781234",
      "email_id": "neha.yadav@example.com",
      "patient_status": "Active",
      "patient_login": "neha_yadav",
      "patient_password": "password303",
      "country": "India",
      "city": "Ghaziabad",
      "district": "Ghaziabad",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "ff1ce9c0-e08a-427d-b1a3-060ae8d187c1",
      "mrn_no": "MRN007",
      "first_name": "Vikram",
      "middle_name": "Singh",
      "last_name": "Rathi",
      "date_of_birth": "1993-09-25",
      "age_in_years": 31,
      "age_in_months": 372,
      "age_in_days": 11160,
      "gender": 1,
      "marital_status": "Single",
      "blood_group": "A-",
      "nationality": "Indian",
      "address": "12, Shankar Lane, Indore, Madhya Pradesh",
      "mobile_no": "+91-9123456789",
      "email_id": "vikram.rathi@example.com",
      "patient_status": "Active",
      "patient_login": "vikram_rathi",
      "patient_password": "password404",
      "country": "India",
      "city": "Indore",
      "district": "Indore",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "fb8720f6-9f13-4cb3-b93d-81fda465bc41",
      "mrn_no": "MRN008",
      "first_name": "Sanya",
      "middle_name": "Chaudhary",
      "last_name": "Bhat",
      "date_of_birth": "1999-07-10",
      "age_in_years": 26,
      "age_in_months": 312,
      "age_in_days": 9390,
      "gender": 2,
      "marital_status": "Single",
      "blood_group": "AB-",
      "nationality": "Indian",
      "address": "15, Kamla Nagar, Bhopal, Madhya Pradesh",
      "mobile_no": "+91-8776655443",
      "email_id": "sanya.bhat@example.com",
      "patient_status": "Active",
      "patient_login": "sanya_bhat",
      "patient_password": "password505",
      "country": "India",
      "city": "Bhopal",
      "district": "Bhopal",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "cceec372-f442-4c25-8f80-53bb3477c099",
      "mrn_no": "MRN009",
      "first_name": "Rahul",
      "middle_name": "Vishal",
      "last_name": "Gupta",
      "date_of_birth": "1996-04-14",
      "age_in_years": 29,
      "age_in_months": 348,
      "age_in_days": 10440,
      "gender": 1,
      "marital_status": "Married",
      "blood_group": "O-",
      "nationality": "Indian",
      "address": "58, Patel Nagar, Mumbai, Maharashtra",
      "mobile_no": "+91-9988776655",
      "email_id": "rahul.gupta@example.com",
      "patient_status": "Active",
      "patient_login": "rahul_gupta",
      "patient_password": "password606",
      "country": "India",
      "city": "Mumbai",
      "district": "Mumbai",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "f3672390-fca0-4a81-9da4-f62f1a2ed31d",
      "mrn_no": "MRN010",
      "first_name": "Neeraj",
      "middle_name": "Kumar",
      "last_name": "Sethi",
      "date_of_birth": "1983-12-30",
      "age_in_years": 41,
      "age_in_months": 492,
      "age_in_days": 14760,
      "gender": 1,
      "marital_status": "Married",
      "blood_group": "B-",
      "nationality": "Indian",
      "address": "23, Sarojini Nagar, Lucknow, Uttar Pradesh",
      "mobile_no": "+91-9876543211",
      "email_id": "neeraj.sethi@example.com",
      "patient_status": "Active",
      "patient_login": "neeraj_sethi",
      "patient_password": "password707",
      "country": "India",
      "city": "Lucknow",
      "district": "Lucknow",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "0949dc34-d3bb-4879-bec6-fd2ce8280f18",
      "mrn_no": "MRN011",
      "first_name": "Ritika",
      "middle_name": "Mehta",
      "last_name": "Desai",
      "date_of_birth": "1994-10-22",
      "age_in_years": 30,
      "age_in_months": 360,
      "age_in_days": 10950,
      "gender": 2,
      "marital_status": "Single",
      "blood_group": "A+",
      "nationality": "Indian",
      "address": "65, M.G. Road, Surat, Gujarat",
      "mobile_no": "+91-9911223344",
      "email_id": "ritika.desai@example.com",
      "patient_status": "Active",
      "patient_login": "ritika_desai",
      "patient_password": "password808",
      "country": "India",
      "city": "Surat",
      "district": "Surat",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "c78272e9-49d1-4d8a-a26b-f8a3bf2c4c9c",
      "mrn_no": "MRN012",
      "first_name": "Vishal",
      "middle_name": "Raj",
      "last_name": "Thakur",
      "date_of_birth": "1989-09-10",
      "age_in_years": 35,
      "age_in_months": 420,
      "age_in_days": 12775,
      "gender": 1,
      "marital_status": "Single",
      "blood_group": "AB+",
      "nationality": "Indian",
      "address": "32, Boring Road, Patna, Bihar",
      "mobile_no": "+91-9666554433",
      "email_id": "vishal.thakur@example.com",
      "patient_status": "Active",
      "patient_login": "vishal_thakur",
      "patient_password": "password909",
      "country": "India",
      "city": "Patna",
      "district": "Patna",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "32bd5e43-eef2-4b88-8591-98817d4b8be6",
      "mrn_no": "MRN013",
      "first_name": "Kavya",
      "middle_name": "Raj",
      "last_name": "Kapoor",
      "date_of_birth": "1991-03-15",
      "age_in_years": 34,
      "age_in_months": 408,
      "age_in_days": 12410,
      "gender": 2,
      "marital_status": "Married",
      "blood_group": "B+",
      "nationality": "Indian",
      "address": "11, Green Park, New Delhi",
      "mobile_no": "+91-9876543212",
      "email_id": "kavya.kapoor@example.com",
      "patient_status": "Active",
      "patient_login": "kavya_kapoor",
      "patient_password": "pass123",
      "country": "India",
      "city": "New Delhi",
      "district": "South Delhi",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "14de89ae-5b06-4ddc-b953-329a05c31fe6",
      "mrn_no": "MRN014",
      "first_name": "Amit",
      "middle_name": "Bhushan",
      "last_name": "Mehra",
      "date_of_birth": "1987-07-22",
      "age_in_years": 37,
      "age_in_months": 444,
      "age_in_days": 13505,
      "gender": 1,
      "marital_status": "Married",
      "blood_group": "O+",
      "nationality": "Indian",
      "address": "78, Anna Nagar, Chennai",
      "mobile_no": "+91-9833445566",
      "email_id": "amit.mehra@example.com",
      "patient_status": "Active",
      "patient_login": "amit_mehra",
      "patient_password": "pass234",
      "country": "India",
      "city": "Chennai",
      "district": "Chennai",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "4a9d2c3d-751a-4836-a8f9-d8d15956309f",
      "mrn_no": "MRN015",
      "first_name": "Pooja",
      "middle_name": "Deepak",
      "last_name": "Malhotra",
      "date_of_birth": "1998-05-10",
      "age_in_years": 26,
      "age_in_months": 312,
      "age_in_days": 9510,
      "gender": 2,
      "marital_status": "Single",
      "blood_group": "A-",
      "nationality": "Indian",
      "address": "90, Salt Lake, Kolkata",
      "mobile_no": "+91-9777788899",
      "email_id": "pooja.malhotra@example.com",
      "patient_status": "Active",
      "patient_login": "pooja_malhotra",
      "patient_password": "pass345",
      "country": "India",
      "city": "Kolkata",
      "district": "Kolkata",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "e730484a-906c-4d75-a3ea-1861202383fd",
      "mrn_no": "MRN016",
      "first_name": "Aditya",
      "middle_name": "Narayan",
      "last_name": "Chopra",
      "date_of_birth": "1990-11-18",
      "age_in_years": 34,
      "age_in_months": 408,
      "age_in_days": 12410,
      "gender": 1,
      "marital_status": "Single",
      "blood_group": "B-",
      "nationality": "Indian",
      "address": "33, Bandra West, Mumbai",
      "mobile_no": "+91-9001122233",
      "email_id": "aditya.chopra@example.com",
      "patient_status": "Active",
      "patient_login": "aditya_chopra",
      "patient_password": "pass456",
      "country": "India",
      "city": "Mumbai",
      "district": "Mumbai",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "8ba71b71-fcff-4c30-bc0a-b2f9e815352d",
      "mrn_no": "MRN017",
      "first_name": "Sneha",
      "middle_name": "Anil",
      "last_name": "Nair",
      "date_of_birth": "1993-01-07",
      "age_in_years": 32,
      "age_in_months": 384,
      "age_in_days": 11720,
      "gender": 2,
      "marital_status": "Married",
      "blood_group": "O+",
      "nationality": "Indian",
      "address": "56, Vyttila, Kochi",
      "mobile_no": "+91-9898989898",
      "email_id": "sneha.nair@example.com",
      "patient_status": "Active",
      "patient_login": "sneha_nair",
      "patient_password": "pass567",
      "country": "India",
      "city": "Kochi",
      "district": "Ernakulam",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "f4e09816-de68-4816-bc2a-65f5b7dd2b63",
      "mrn_no": "MRN018",
      "first_name": "Manish",
      "middle_name": "Raghav",
      "last_name": "Saxena",
      "date_of_birth": "1984-04-30",
      "age_in_years": 41,
      "age_in_months": 492,
      "age_in_days": 14965,
      "gender": 1,
      "marital_status": "Married",
      "blood_group": "AB-",
      "nationality": "Indian",
      "address": "45, Rajajipuram, Lucknow",
      "mobile_no": "+91-9897979797",
      "email_id": "manish.saxena@example.com",
      "patient_status": "Active",
      "patient_login": "manish_saxena",
      "patient_password": "pass678",
      "country": "India",
      "city": "Lucknow",
      "district": "Lucknow",
      "deceased_date": "",
      "deceased_reason": ""
    },
   {
      "patientId": "9655527b-e893-4f06-86a7-113e1d666815",
      "mrn_no": "MRN019",
      "first_name": "Isha",
      "middle_name": "Vikas",
      "last_name": "Tiwari",
      "date_of_birth": "1995-12-03",
      "age_in_years": 29,
      "age_in_months": 348,
      "age_in_days": 10620,
      "gender": 2,
      "marital_status": "Single",
      "blood_group": "A+",
      "nationality": "Indian",
      "address": "101, Adarsh Nagar, Jaipur",
      "mobile_no": "+91-9333322222",
      "email_id": "isha.tiwari@example.com",
      "patient_status": "Active",
      "patient_login": "isha_tiwari",
      "patient_password": "pass789",
      "country": "India",
      "city": "Jaipur",
      "district": "Jaipur",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "a94d3ca2-3429-4e65-afe7-a971cedbee71",
      "mrn_no": "MRN020",
      "first_name": "Rohit",
      "middle_name": "Suresh",
      "last_name": "Pillai",
      "date_of_birth": "1992-09-20",
      "age_in_years": 32,
      "age_in_months": 384,
      "age_in_days": 11700,
      "gender": 1,
      "marital_status": "Single",
      "blood_group": "B+",
      "nationality": "Indian",
      "address": "17, Panvel, Navi Mumbai",
      "mobile_no": "+91-9555666777",
      "email_id": "rohit.pillai@example.com",
      "patient_status": "Active",
      "patient_login": "rohit_pillai",
      "patient_password": "pass890",
      "country": "India",
      "city": "Navi Mumbai",
      "district": "Raigad",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "74f82ca6-0d14-4951-a825-6bc4eb956a8c",
      "mrn_no": "MRN021",
      "first_name": "Divya",
      "middle_name": "Mohan",
      "last_name": "Kulkarni",
      "date_of_birth": "1989-02-14",
      "age_in_years": 36,
      "age_in_months": 432,
      "age_in_days": 13140,
      "gender": 2,
      "marital_status": "Married",
      "blood_group": "O-",
      "nationality": "Indian",
      "address": "29, Jayanagar, Bangalore",
      "mobile_no": "+91-9111122233",
      "email_id": "divya.kulkarni@example.com",
      "patient_status": "Active",
      "patient_login": "divya_kulkarni",
      "patient_password": "pass901",
      "country": "India",
      "city": "Bangalore",
      "district": "Bangalore",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "e8da14a8-6d72-48df-b8fe-2443605a45d8",
      "mrn_no": "MRN022",
      "first_name": "Karan",
      "middle_name": "Dev",
      "last_name": "Sundar",
      "date_of_birth": "1997-06-01",
      "age_in_years": 27,
      "age_in_months": 324,
      "age_in_days": 9845,
      "gender": 1,
      "marital_status": "Single",
      "blood_group": "A-",
      "nationality": "Indian",
      "address": "88, Gandhi Chowk, Amritsar",
      "mobile_no": "+91-9090909090",
      "email_id": "karan.sundar@example.com",
      "patient_status": "Active",
      "patient_login": "karan_sundar",
      "patient_password": "pass012",
      "country": "India",
      "city": "Amritsar",
      "district": "Amritsar",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "3de61b19-6408-4193-8569-fa5db3ab75ef",
      "mrn_no": "MRN023",
      "first_name": "Tanvi",
      "middle_name": "Ashok",
      "last_name": "Bhattacharya",
      "date_of_birth": "1996-11-25",
      "age_in_years": 28,
      "age_in_months": 336,
      "age_in_days": 10220,
      "gender": 2,
      "marital_status": "Single",
      "blood_group": "B+",
      "nationality": "Indian",
      "address": "66, Ballygunge, Kolkata",
      "mobile_no": "+91-9988776655",
      "email_id": "tanvi.bhattacharya@example.com",
      "patient_status": "Active",
      "patient_login": "tanvi_bhattacharya",
      "patient_password": "pass1234",
      "country": "India",
      "city": "Kolkata",
      "district": "Kolkata",
      "deceased_date": "",
      "deceased_reason": ""
    },
    {
      "patientId": "b5270f80-c53f-4597-94ae-add2667e45bb",
      "mrn_no": "MRN024",
      "first_name": "Rajesh",
      "middle_name": "Nitin",
      "last_name": "Shetty",
      "date_of_birth": "1985-05-08",
      "age_in_years": 40,
      "age_in_months": 480,
      "age_in_days": 14600,
      "gender": 1,
      "marital_status": "Married",
      "blood_group": "O+",
      "nationality": "Indian",
      "address": "49, Kadri, Mangalore",
      "mobile_no": "+91-9878987878",
      "email_id": "rajesh.shetty@example.com",
      "patient_status": "Active",
      "patient_login": "rajesh_shetty",
      "patient_password": "pass5678",
      "country": "India",
      "city": "Mangalore",
      "district": "Dakshina Kannada",
      "deceased_date": "",
      "deceased_reason": ""
    }
  ]



  export let l_investigation_list = [
    {
        "investigationLevelId": "b9e374f7-ef39-4251-8ff5-28479f8c2d7e",
        "investigationLevel1Name": "CBC (Complete Blood Count)",
        "unit": "",
        "referenceRange": "",
        "type": "Panel",
    },
    {
        "investigationLevelId": "9960cb7b-5dd5-43ec-9754-4ace88ef6ade",
        "investigationLevel1Name": "Platelet Count",
        "unit": "x10^3/µL",
        "referenceRange": "150-450",
        "type": "Test"
    },
    {
        "investigationLevelId": "0411e2a3-88b0-457f-848c-ca5d8709d8e1",
        "investigationLevel1Name": "Coagulation Tests",
        "unit": "N/A",
        "referenceRange": "Varies by test",
        "type": "Panel"
    },
    {
        "investigationLevelId": "90ca5f64-7591-4044-a6a5-1a34e755f54d",
        "investigationLevel1Name": "Iron Studies",
        "unit": "N/A",
        "referenceRange": "Varies by test",
        "type": "Panel"
    }
]


//! Send This type of payload for report print
let l_request_scheduled_report_payload={
    "jobKey": "",
    "jobName": "daily_report",
    "cronExpression": "0 20 0 * * ?",
    "parameters": {
      "reportType": "Inventory",
      "startDate": "2025-04-29",
      "endDate": "2025-04-29",
      "hospitalId": 111,
      "includeSummary": true
    }
}